sudo: false
language: node_js
node_js:
  - stable

services:
  - mongodb

script: 
  - npm test
  
after_success:
  - npm run cover
  - bash <(curl -s https://codecov.io/bash)

before_script:
  - sudo /etc/init.d/mongod start

